import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const appName = process.env.APP_NAME || "Waifu.im";

// The API sidebar is auto-generated by docusaurus-plugin-openapi-docs.
// Run `npm run gen-api-docs` to generate it from the OpenAPI spec.
let apiSidebarItems: object[] = [];
try {
  apiSidebarItems = require("./docs/api/sidebar");
} catch {
  // Not generated yet - run: npm run gen-api-docs
}

const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    "getting-started",
    "authentication",
    "rate-limiting",
    "versioning",
    "tags",
    "terms-of-service",
  ],
  api: [
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "generated-index",
        title: `${appName} API Reference`,
        description: `The complete API reference for ${appName}, auto-generated from the OpenAPI specification.`,
        slug: "/category/api",
      },
      items: ["api-intro", ...apiSidebarItems],
    },
  ],
};

export default sidebars;
